spring.application.name=springbootapp

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/users
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (recommended)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server (avoid port issue)
server.port=8081
openai.api.key=YOUR_API_KEY_HERE